from __future__ import annotations

import inspect
import math
import re
import secrets
from collections.abc import Callable
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from typing import TypeAlias

from PIL import Image, ImageOps

from . import adapters
from .adapters import AdapterUse
from .catalog import Asset, Prompt, get_asset, sha256_text
from .config import QWEN_REFERENCE_RESOLUTION, ModelId
from .registry import MODEL_REGISTRY
from .runtime import _STATE


def slugify(value: str) -> str:
    value = re.sub(r"[^a-z0-9._-]+", "-", value.strip().lower())
    return re.sub(r"-+", "-", value).strip("-._") or "image"


def round_to_multiple(value: int, multiple: int) -> int:
    return max(multiple, int(round(value / multiple) * multiple))


@dataclass(frozen=True)
class ImageUse:
    source: Asset | Image.Image
    strength: float | None = None


@dataclass
class _WorkflowContext:
    images: list[ImageUse] = field(default_factory=list)
    adapters: list[AdapterUse] = field(default_factory=list)
    size: tuple[int, int] | None = None
    steps: int | None = None
    guidance: float | None = None
    sampler: str | None = None
    negative_prompt: str | Prompt | None = None
    batch: int | None = None
    output_name: str | None = None


_CURRENT_WORKFLOW: ContextVar[_WorkflowContext | None] = ContextVar(
    "_CURRENT_WORKFLOW", default=None
)
Workflow: TypeAlias = Callable[[], str | Prompt]


def _context() -> _WorkflowContext:
    context = _CURRENT_WORKFLOW.get()
    if context is None:
        raise RuntimeError("use_*() functions must be called inside draw(workflow).")
    return context


def use_image(
    asset: Asset | str | Image.Image, *, strength: float | None = None
) -> None:
    """Add an ordered image reference to the current workflow."""
    if isinstance(asset, str):
        asset = get_asset(asset)
    if isinstance(asset, Asset) and asset.kind != "image":
        raise TypeError(f"use_image() requires an image asset, got {asset.kind!r}")
    if not isinstance(asset, (Asset, Image.Image)):
        raise TypeError("use_image() requires an image asset, asset ID, or PIL image")
    if strength not in (None, 1.0):
        raise NotImplementedError(
            "Reference strength currently supports only None or 1.0."
        )
    # Hold a snapshot so later changes to the caller's image cannot change this draw.
    source = asset.copy() if isinstance(asset, Image.Image) else asset
    _context().images.append(ImageUse(source=source, strength=strength))


def use_adapter(name: str, strength: float = 1.0) -> None:
    """Apply an indexed adapter to the current workflow."""
    record = adapters._get_adapter(name)
    strength = float(strength)
    if not -100.0 <= strength <= 100.0:
        raise ValueError("Adapter strength must be between -100 and 100.")
    _context().adapters.append(AdapterUse(record.id, strength))


def use_size(width: int, height: int) -> None:
    """Override the model's default output dimensions."""
    if width <= 0 or height <= 0:
        raise ValueError("width and height must be positive")
    _context().size = (int(width), int(height))


def use_steps(steps: int) -> None:
    """Override the model's default sampling-step count."""
    steps = int(steps)
    if steps <= 0:
        raise ValueError("steps must be positive")
    _context().steps = steps


def use_guidance(guidance: float) -> None:
    """Override the model's default guidance value."""
    guidance = float(guidance)
    if guidance < 0:
        raise ValueError("guidance must be nonnegative")
    _context().guidance = guidance


def use_sampler(name: str) -> None:
    """Select the sampler for the current workflow."""
    name = str(name).strip()
    if not name:
        raise ValueError("sampler name must not be empty")
    _context().sampler = name


def use_negative_prompt(prompt: str | Prompt) -> None:
    """Set the negative prompt for the current workflow."""
    _context().negative_prompt = prompt


def use_batch(batch: int) -> None:
    """Set the number of images generated by the current draw."""
    batch = int(batch)
    if batch <= 0:
        raise ValueError("batch must be positive")
    _context().batch = batch


def use_output_name(name: str) -> None:
    """Set the filename prefix used for saved images."""
    name = str(name).strip()
    if not name:
        raise ValueError("output name must not be empty")
    _context().output_name = name


def reference_output_size(
    source: Path | Image.Image, *, total_pixels: float, multiple: int
) -> tuple[int, int]:
    if isinstance(source, Path):
        with Image.open(source) as image:
            width, height = ImageOps.exif_transpose(image).size
    else:
        width, height = ImageOps.exif_transpose(source).size
    scale = math.sqrt(total_pixels / (width * height))
    return (
        round_to_multiple(round(width * scale), multiple),
        round_to_multiple(round(height * scale), multiple),
    )


@dataclass(frozen=True)
class _DrawSpec:
    model_id: ModelId
    prompt: str
    prompt_obj: Prompt | None
    workflow_name: str
    workflow_source_sha256: str | None
    images: tuple[ImageUse, ...]
    adapters: tuple[AdapterUse, ...]
    seed: int
    width: int
    height: int
    size_explicit: bool
    steps: int
    guidance: float
    sampler: str
    negative_prompt: str
    batch: int
    output_name: str
    saving_enabled: bool


def _workflow_source_hash(workflow: Workflow) -> str | None:
    try:
        return sha256_text(inspect.getsource(workflow))
    except Exception:
        return None


def _resolve_workflow(workflow: Workflow) -> _DrawSpec:
    model_id = _STATE.model.get("model_id")
    if model_id is None:
        raise RuntimeError("No active model. Call load_model() first.")
    if _CURRENT_WORKFLOW.get() is not None:
        raise RuntimeError("Nested draw() calls are not supported.")
    context = _WorkflowContext()
    token = _CURRENT_WORKFLOW.set(context)
    try:
        returned = workflow()
    finally:
        _CURRENT_WORKFLOW.reset(token)
    if not isinstance(returned, str):
        raise TypeError("A workflow must return str or Prompt.")
    prompt_text = str(returned).strip()
    if not prompt_text:
        raise ValueError("A workflow returned an empty prompt.")
    prompt_obj = returned if isinstance(returned, Prompt) else None
    model_cfg = MODEL_REGISTRY[model_id]
    resolved = dict(model_cfg["defaults"])
    size_explicit = context.size is not None
    if context.size is not None:
        resolved["width"], resolved["height"] = context.size
    elif context.images and not size_explicit:
        first_source = context.images[0].source
        reference = (
            first_source.path if isinstance(first_source, Asset) else first_source
        )
        resolved["width"], resolved["height"] = reference_output_size(
            reference,
            total_pixels=QWEN_REFERENCE_RESOLUTION**2,
            multiple=32,
        )
    for name in ("steps", "guidance", "sampler", "batch"):
        value = getattr(context, name)
        if value is not None:
            resolved[name] = value
    if context.negative_prompt is not None:
        resolved["negative_prompt"] = str(context.negative_prompt)
    if context.output_name is not None:
        resolved["output_name"] = context.output_name
    max_references = model_cfg["max_references"]
    if max_references is not None and len(context.images) > max_references:
        raise ValueError(
            f"{model_cfg['display_name']} supports at most {max_references} references."
        )
    seed = _STATE.random_seed
    if seed is None:
        seed = secrets.randbelow(2**63)
    workflow_name = getattr(workflow, "__name__", "workflow")
    default_name = prompt_obj.id if prompt_obj is not None else workflow_name
    merged_adapters = {item.id: item for item in adapters.DEFAULT_ADAPTERS}
    for item in context.adapters:
        if item.strength == 0:
            merged_adapters.pop(item.id, None)
        else:
            merged_adapters[item.id] = item
    for item in merged_adapters.values():
        adapters._get_adapter(item.id)
    multiple = int(model_cfg["size_multiple"])
    return _DrawSpec(
        model_id=model_id,
        prompt=prompt_text,
        prompt_obj=prompt_obj,
        workflow_name=workflow_name,
        workflow_source_sha256=_workflow_source_hash(workflow),
        images=tuple(context.images),
        adapters=tuple(merged_adapters.values()),
        seed=int(seed),
        width=round_to_multiple(int(resolved["width"]), multiple),
        height=round_to_multiple(int(resolved["height"]), multiple),
        size_explicit=size_explicit,
        steps=int(resolved["steps"]),
        guidance=float(resolved["guidance"]),
        sampler=str(resolved["sampler"]),
        negative_prompt=str(resolved.get("negative_prompt", "")),
        batch=int(resolved["batch"]),
        output_name=slugify(str(resolved.get("output_name", default_name))),
        saving_enabled=_STATE.saving_enabled,
    )
